# Exercise 18
# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
# For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. Keep track of the number of guesses 
# the user makes throughout the game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random
import myFunctions

def digits(number: int) -> list:
    nList = []
    while number > 0:
        nList.append(number%10)
        number = number//10
    nList.reverse()
    return nList

def compareNumber(number, userNumber):
    result = {
    'cows': 0,
    'bulls': 0
    }
    nList = digits(number)
    digitsList = digits(number)
    for i in range(len(digitsList)):
        if nList[i] == digitsList[i]:
            result['cows'] += 1
        else:
            result['bulls'] += 1
    cows = result.get('cows')
    bulls = result.get('bulls')
    return result
   

def playGame():
    print('''Welcome to the Cows 🐮 and Bulls ♉ Game!
    I will generate a number, and you have to guess the numbers one digit at a time.
    For every number in the wrong place, you get a cow. For every one in the right place, you get a bull.
    The game ends when you get 4 bulls!
    ''')
    secretNumber = random.randint(1000,9999)
    print(secretNumber)
    guesses = 0
    while True:
        userNumber = myFunctions.getInt('Give me your best guess!:')
        result = compareNumber(secretNumber,userNumber)
        guesses += 1
        if result['bulls'] == 4:
            print(f'You win the game after {guesses} 🍾🎉. The number was {secretNumber} ')
            break
        else:
            print('Your guess isn´t quite right, try again!') 

playGame()
